### ISSUE TITLE
AirPlayer crashes the app; & lag and no input on LiveScreen

### ISSUE THREAD

**Issue by samuelawachie** [iDescriptor/iDescriptor#12]
I'm on Linux Zorin 17.3 and an iPhone 6S (iOS 15.8.5)
When tapping on AirPlayer in the Toolbox, the application just crash-closes by itself.
Also, when tapping on LiveScreen, the lag/latency is so much and input with the mouse on the desktop doesn't translate to on-device (it appears this is just an output of the screen on the phone, but doesn't accept any input to the phone). 
As you can perhaps deduce, those are the two functions I was interested in this (playing media on my phone and having it on the laptop's bigger screen), and none are satisfactory for now and my use-case remains unfulfilled.

**Comment by uncor3** [comment]
Hi, LiveScreen is not meant to send your mouse or keyboard inputs to device, the way it works is by capturing screenshots at a fixed interval (20 FPS) , going above 20 FPS doesnt do any good because it seems to be an api limitation,  there is no such api for developers to send mouse or keyboard inputs to iDevice other than using Bluetooth which is not implemented yet, for the crash i can say wait for Flatpak version which is going to pushed today

**Comment by 7DSMeliodas** [comment]
> Hi, LiveScreen is not meant to send your mouse or keyboard inputs to device, the way it works is by capturing screenshots at a fixed interval (20 FPS) , going above 20 FPS doesnt do any good because it seems to be an api limitation, there is no such api for developers to send mouse or keyboard inputs to iDevice other than using Bluetooth which is not implemented yet, for the crash i can say wait for Flatpak version which is going to pushed today

macOS 26.1 here same problem with AirPlayer

**Comment by samuelawachie** [comment]
> macOS 26.1 here same problem with AirPlayer
>
Hey, have you tried the new version? Is it still crashing when trying to use AirPlayer?

**Comment by may-ushii** [comment]
This is happening to me on Windows 11. Airplay just immediately crashes the application.

**Comment by xrickbennetx** [comment]
It’s kinda crazy you think I’m cursing someone out when I just ask a question. Honestly kinda a miracle you can type since you have 0 reading comprehension skills 👍

**Comment by samuelawachie** [comment]
> It’s kinda crazy you think I’m cursing someone out when I just ask a question. Honestly kinda a miracle you can type since you have 0 reading comprehension skills 👍
> 
Going to my profile and navigating to all my posts/comments to downvote them. You're a funny fella my dear :)

**Comment by armand06-cmd** [comment]
I also have the same issue. I'm trying to AirPlay from my iPhone 15PM, and it's making the app crash. I've tried multiple times, but the app always crashes when trying to AirPlay my screen to my computer. By the way, I'm on the latest version available.

**Comment by uncor3** [comment]
@armand06-cmd If you can provide some logs I may be able help

**Comment by uncor3** [comment]
Fixed in [v0.6.0](https://github.com/iDescriptor/iDescriptor/releases#release-v0.6.0) , please consider supporting the project https://opencollective.com/idescriptor. Thanks!

**Comment by samuelawachie** [comment]
> Fixed in [v0.6.0](https://github.com/iDescriptor/iDescriptor/releases#release-v0.6.0) , please consider supporting the project https://opencollective.com/idescriptor. Thanks!
>
Air player is still crashing. Live screen is working! I tried Live screen and found the frame rate disappointing as there was just so much lag and it was too pixelated. I went to settings and saw that one could edit the fps of the AIr player. I set that to 30 from the default of 60 it had been set, hoping to get smoother and better mirror of the Live Screen, but it didn't seem to have any effect.
How can I make the Livescreen tool better quality? At least it's showing now, and fulfills a major part of why I got the program. Just that the lag is too much, and video quality is not good enough when stuff's playing on the phone and mirrored to the desktop.
Does the setting of fps for Airplayer affect Livescreen?

**Comment by samuelawachie** [comment]
Had to use uxplay to get native airplayer functioning actually. And to get it to play without stuttering video or audio use these options
uxplay -avdec  -s 1388x768@15 -vsync no

**Comment by uncor3** [comment]
@samuelawachie that fps setting is for AirPlay not for Livescreen, if you can provide some logs I may be able help you. Livescreen cannot go above 15 fps because iOS doesn't let that happen. I tried it on Ubuntu, Debian, Arch Linux it works just fine I don't really understand why it crashes under Zorin

**Comment by uncor3** [comment]
@samuelawachie try installing from flathub https://flathub.org/en/apps/io.github.idescriptor.iDescriptor , if it still crashes i don't what could be wrong honestly
